### ISSUE TITLE
possible small improvement to the readme.md about sample inputs for new datasets

### ISSUE THREAD

**Issue by sonebu** [MaximIntegratedAI/ai8x-synthesis#150]
Section "Generating a Random Sample Input" provides the following line as an example:

`np.save(os.path.join('tests', 'sample_mnist'), a, allow_pickle=False, fix_imports=False)`

where `a` is a random tensor initialized explicitly as `dtype=np.int64` in the previous line. The input being of an integer type seems to be important for the synthesis tool because it fails at the "bitwise and" operator inside the parameter load function in izer/load.py at this [line](https://github.com/MaximIntegratedAI/ai8x-synthesis/blob/ff4368979e1ea5b2d9dd84563973b949e47bbec3/izer/load.py#L242) when the type is e.g., float64. The example already uses an input cast to int64, which gives a hint, but the error message when you don't use an int type is pretty cryptic:  

> ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

and it was a bit cumbersome to trace the izer/... files to understand that my input wasn't saved with the correct type (I just copied the line I pasted above to save my sample data for a new dataset, which therefore skipped the typecasting, and numpy defaulted to float64 even though I had 256 unique values in the -128...+127 range). So my suggestion: 

- maybe a very small note under Section "Generating a Random Sample Input" in the readme.md, reiterating that the data should be dtype=np.int64

- or, even though it's redundant, adding an explicit typecast to the "saving line" in the example (which everybody will probably copy without reading the randgen line, like me):

`np.save(os.path.join('tests', 'sample_mnist'), a.astype('int64'), allow_pickle=False, fix_imports=False)`

the second suggestion might induce even worse "hidden" errors like casting float input data in small ranges to int64 without notice, flooring them all to 0, -1 etc. though (depending on rounding settings), so I personally vote for the first one

**Comment by rotx-maxim** [comment]
Thanks for your suggestion. #151 should address this.
