### ISSUE TITLE
Documentation improvement : end-to-end deployment

### ISSUE THREAD

**Issue by Narduzzi** [MaximIntegratedAI/ai8x-synthesis#182]
Hello,

I would like to deploy a model on the MAX78000FTHR Board.
While the documentation is really complete (thank you!), it is a bit dense and I have trouble finding relevant information.
Specifically, once the project is built, I don't know how to test it on the device.

For the purpose of benchmarking, I would like to deploy a set of models on the board and get a few information (speed, accuracy, latency, power consumption) for each model. How can I achieve this?

Would it be possible to write a special section, or maybe a wiki, about how to deploy a model from PyTorch to the device, and get the output of the model?

Thanks for your help!

**Comment by rotx-maxim** [comment]
Measuring power (and energy) can be really tricky, especially on devices that have a large dynamic range.
We recommend using the power monitor on our EVKit. Please see https://www.maximintegrated.com/en/design/technical-documents/app-notes/7/7417.html for more information.

To load a deployed model, please follow the steps in https://github.com/MaximIntegratedAI/MaximAI_Documentation/tree/master/MAX78000_Evaluation_Kit#getting-started-with-the-max78000-evaluation-kit-ev-kit
