### ISSUE TITLE
Chaining of Linear Layers

### ISSUE THREAD

**Issue by gihug-git** [MaximIntegratedAI/ai8x-synthesis#194]
Hi there! 

I am currently working on a project with the goal to port an existing model onto the MAX78000 platform due to its advanced convolution abilities. Everything works just fine except the last two layers of the net which consist of two linear layers back to back. 

According to the readme.md the chaining of linear layers is possible when omitting the 'flatten' step. I am assuming that the first Linear Layer requires a 'flatten' operation but the following linear layers do not, is that correct? Sadly I did not find any examples with more than one linear layer in series.
Anyway I tried a lot of different setups using different values for flatten, in_dim, in_channel etc. but it does not seem to work. It seems like the second linear layer has trouble with the output of the first linear layer which comes as 1x1 features - m channels. The output of the ai8xize.py script is as follows:

```
Configuring device: MAX78000
Reading ../../network_path.yaml to configure network...
Reading ../../pth_path.tar to configure network weights...
Checkpoint for epoch 1, model pth - weight and bias data:
 InCh OutCh  Weights         Quant Shift  Min  Max   Size Key                                       Bias       Quant  Min  Max Size Key
   16    20  (320, 1)            8    -2 -126  127    320 Convs.0.weight                            (20,)          8  -86  115   20 Convs.0.bias
   20    20  (400, 2)            8 N/A    -81   81    800 Convs.1.weight                            (20,)          8  -77   77   20 Convs.1.bias
   20    20  (400, 2)            8    -2  -81   81    800 Convs.2.weight                            (20,)          8  -68   71   20 Convs.2.bias
   20    20  (400, 2)            8 N/A    -81   81    800 Convs.3.weight                            (20,)          8  -68   77   20 Convs.3.bias
  100    32  (1, 32, 100)        8 N/A   -102  102   3200 Lins.0.weight                             (32,)          8  -95  102   32 Lins.0.bias
   32    10  (1, 10, 32)         8    -2  -89   90    320 Lins.1.weight                             (10,)          8  -78   82   10 Lins.1.bias
TOTAL: 6 parameter layers, 6,362 parameters, 6,362 bytes
Configuring data set: Dataset.
prefix...
WARNING: --overwrite specified, writing to sdk/Examples/MAX78000/CNN/prefix even though it exists.
ERROR: The configured kernel dimensions (1x1) for layer 11 do not match the weights file (32x10)!
```

with the last three layers in the yaml file looking as follows:

```
# Layer 9: add
- operation: Add
  in_offset: 0x0000
  out_offset: 0x2000
  in_sequences: [7, 8]
  processors: 0xfffff00000000
  output_processors: 0xfffff00000000

# Layer 10: Flatten + Linear
- operation: MLP
  flatten: true
  activation: ReLU
  in_offset: 0x2000
  out_offset: 0x0000
  processors: 0x000fffff

# Layer 11: Linear
- operation: MLP
  activation: None
  out_offset: 0x2000
  output_width: 32
  processors: 0xffffffff00000000
```

It is very strange since the 'flatten' before the first layer also rearranges the features (features arranged in HxWxC and not only in 1x1xm where m =C*W*H) and it matches the dimesnions of the wieghts without a problem and in the second layer it does not.

Any advice is highly appreciated.

**Comment by rotx-maxim** [comment]
Thanks for the report. This should be supported by the hardware and if so we will fix this in the tool.
A workaround might be specifying "flatten: true" for the second linear layer. Could you try that and report back please?
