### ISSUE TITLE
Synthesis Answer

### ISSUE THREAD

**Issue by Doruk-Dilmen** [MaximIntegratedAI/ai8x-synthesis#234]
some things stick in my mind about synthesis
First of all, why we are doing this;
`(ai8x-synthesis) $ python quantize.py proj/qat_best.pth.tar proj/proj_q8.pth.tar --device MAX78000`

In the second place;
`python ai8xize.py --verbose --test-dir demos --prefix ai85-kws20 --checkpoint-file proj/proj_q8.pth.tar --config-file networks/kws20-hwc.yaml --device MAX78000 --compact-data --mexpress --softmax`
then cnn.c cnn.h weight.h softmax.c file is created. But how are these files created? I want to understand. And what do these files mean?

**Comment by rotx-maxim** [comment]
For the basic structure of the pipeline, please check out our video series at https://www.maximintegrated.com/en/products/microcontrollers/artificial-intelligence.html/tab4

Regarding the file names you mentioned, please check the documentation at https://github.com/MaximIntegratedAI/ai8x-training#readme
