### ISSUE TITLE
Sound Problem

### ISSUE THREAD

**Issue by Doruk-Dilmen** [MaximIntegratedAI/ai8x-synthesis#248]
Hi,

I'm trying to the card make a some sound after the card detect a word. Would you give me the way or help?

**Comment by aniktash** [comment]
[CODEC-Out.zip](https://github.com/MaximIntegratedAI/ai8x-synthesis/files/9113485/CODEC-Out.zip)
This is an example of playing a tone with codec coming out of line-out audio jack (J7)

**Comment by Doruk-Dilmen** [comment]
There is something wrong. Such as

You defined micEn end micSel:
![image](https://user-images.githubusercontent.com/91119666/180734225-62758485-0df5-4c58-ad92-f6d5553dbf34.png)
But there is not :
![image](https://user-images.githubusercontent.com/91119666/180734470-43090fab-6651-40c9-8da3-263ad5c4e05a.png)


I defined like you:
![image](https://user-images.githubusercontent.com/91119666/180735456-76a1497d-c521-4c7e-b329-c4c8adc3516e.png)
But I took error: 'audioFile' undeclared :
![image](https://user-images.githubusercontent.com/91119666/180735565-da475df9-12ad-4eba-b082-8427208fefb7.png)

**Comment by aniktash** [comment]
WavFile_t is defined in the audio.h of the project and is included at the top:

#include "tmr.h"

#include "audio.h"

static WavFile_t audioFile;

/***** Definitions *****/

**Comment by Doruk-Dilmen** [comment]
Only, leds are changing like this, no audio output:
![image](https://user-images.githubusercontent.com/91119666/181242814-0c16d0dd-6d41-432a-ac44-288280a53096.png)
![image](https://user-images.githubusercontent.com/91119666/181242863-77af5d7a-7d51-426c-af09-0f6008030286.png)

**Comment by Doruk-Dilmen** [comment]
Hi, 

Would you share CODEC input example? Please.

**Comment by Doruk-Dilmen** [comment]
Hi,

Could you share the codec entry example? Please.
