### ISSUE TITLE
Which register specifies a master quadrant for calculating sum-of-products?

### ISSUE THREAD

**Issue by hyunjongL** [MaximIntegratedAI/ai8x-synthesis#254]
I got a few questions while going through the user guide of MAX78000.

1. How is the master quadrant selected, which collects the partial sum-of-products, calculates the sum of all products, and writes to the next layer? 
(I have a feeling that it is the first quadrant (or the first processor) by looking at mnist-chw-ai85.yaml file where it avoids to use the first quadrant throughtout several layers.)

2. Also, is there any difference in performance if we choose to/not to run convolution on the master quadrants?

3. Can we parallelize computation for more processors when we have less channels? If I only have 32 channels to compute and have 60 output channels, can I parallelize the computation to the entire 64 processors?

4. Why doesn't the cifar-100 example not use parallel mode for the first layer? For example, by using processors 0x111 instead of 0x007 and input the data to three memories. If it is because of the channel format (HWC), is it more costly to change the format to (CHW) than the merit of running this in three parallel groups?

Many thanks!

**Comment by hyunjongL** [comment]
One additional question: on page 402 in user guide for max78000, the Layer Row Count Maximum is calculated as follows, but what I see from the example is 1 smaller. 
> rcnt_max = (2 × rcnt_pad) + number_of_rows

Shouldn't it be as below, because the count will start from 0?
> rcnt_max = (2 × rcnt_pad) + number_of_rows - 1

**Comment by rotx-maxim** [comment]
1. The master quadrant is selected using a control bit (in the control register). The tools automatically select a master quadrant. There is also a hardware limitation for some operations that require the master quadrant to be quadrant 0.
2. No, there is no difference.
3. This is not supported, you would have to train with the modified input (for example, you could perhaps designate the first half of your output data channels 0-31 and the second half as channels 32-64). This is obviously not mathematically identical, but it's possible that the model would train (and then you could run it).
4. The choice of HWC vs CHW is primarily the user's choice and depends on the input data format which can be very costly to change from one to the other.

Thank you for pointing out the user guide mistake. We will get it corrected.
