### ISSUE TITLE
Can I set 4 processors for 8 channels?

### ISSUE THREAD

**Issue by hyunjongL** [MaximIntegratedAI/ai8x-synthesis#257]
I know the synthesis in the current form does not support this, however, is there a way to run two pass for less processors by setting the registers? (I am comfortable with the registers on the accelerator, so you can explain using them)

**Comment by rotx-maxim** [comment]
Yes, try the "--max-proc" command line option. For example, "--max-proc 32". This is not officially supported, so it's possible you'll run into problems. Let me know if that happens.

**Comment by hyunjongL** [comment]
If I synthesize 2 models for 32 processors each, it will each have configurations for 32 processors.
Can the two be allocated for processors 0-31 and 32-63?
They would have different row/column count registers and will have settings for themselves. 
Problems I can imagine is when the aggregator tries to fetch data from all 64 processors, or when the processors would want run in sync.

**Comment by rotx-maxim** [comment]
Correct, unfortunately this is not supported in the general sense.

**Comment by hyunjongL** [comment]
Thanks!!
I think I got a somewhat understanding. I just need to process on how the aggregator works.
