### ISSUE TITLE
YAML file

### ISSUE THREAD

**Issue by salihtangel** [MaximIntegratedAI/ai8x-synthesis#261]
In synthesies  i get this error  "Layer 8: 3 input channels (before flattening) using 1 pass, and 1 operand (3 processors per pass), but the enabled processor map 0x00000000ffffffff has 32 bits instead of the expected number of 3."  I could not solved it. Can you share a yaml file for ai85kws20netv2batchnorm model?

**Comment by aniktash** [comment]
Make sure to use the same model for training and synthesis. 
The v3 model is used in demo application, which is much smaller than v2.  If you want to use v2 model with batchnorm:
1-  In training and evaluate v2 script, change the model and add bias:  --model ai85kws20netv2batchnorm --use-bias
2- Copy the kws20-v2-hwc.yaml as kws20-v2-batchnorm-hwc.yaml
3- In kws20-v2-batchnorm-hwc.yaml file, change arch name to match the batchnorm model:  arch: ai85kws20netv2batchnorm
4- in synthesis script use this new yaml:   --config-file networks/kws20-v2-batchnorm-hwc.yaml
