### ISSUE TITLE
CNN.c

### ISSUE THREAD

**Issue by oussemajelassi** [MaximIntegratedAI/ai8x-synthesis#262]
As I get it CNN.c is basically a driver for for the accelerator and it has necessary functions to load the data etc..
What I missed is why those functions generated after the synthesis ? are they network/data independent and why is that ?

**Comment by rotx-maxim** [comment]
The functions in cnn.c are network and weight dependent. However, the function signatures (cnn.h) do not change. This allows the user to design an application and replace the underlying CNN with little work. Please also see "Generating C Code" in README.md.
