### ISSUE TITLE
--sample-input doesn't work for me

### ISSUE THREAD

**Issue by Doruk-Dilmen** [MaximIntegratedAI/ai8x-synthesis#274]
Hi,

I am trying to synthesis part with `--sample-input.` I created sample_kws_20.npy , using `--save-sample 10 `argument. However, I take this returned.
![image](https://user-images.githubusercontent.com/91119666/199660671-94386ba8-46a4-4c07-94d0-4597298b57f0.png)

**Comment by aniktash** [comment]
Make sure you have quantized the checkpoint and that you are using the quantized checkpoint to evaluate, create sample data and synthesize. Also, to create the sample data, you should use -8 (similar to the evaluation script).

**Comment by Doruk-Dilmen** [comment]
Thank you.

I want to ask one more thing. I am using `--save-sample 10` argument. What's in class 20.? Which class?

**Comment by aniktash** [comment]
The index used in --save-sample is not the class, it's the index to a sample data in the dataloader. So, you cannot quickly figure out which class that sample is taken from.

**Comment by Doruk-Dilmen** [comment]
Okey, I got it but how can I know my network is working correctly. I think I should know which class that sample is taken from.
Then I have to check if this is true. Finally, based on the result of this, I decide whether my network is working correctly or not.

**Comment by aniktash** [comment]
The purpose of this sample data is to integrate with the c code and test it on HW as the known answer test. A pass means that the network on HW behaves exactly the same as your model. You can evaluate your model independently to see if it works correctly. You also can manually convert a 1sec wav to a 128x128 tensor saved as .npy for sample data. Keep in mind that sequential audio samples range are stored in columns in the tensor and are in [-128,127] range. A notebook example is provided here: https://github.com/MaximIntegratedAI/ai8x-training/blob/develop/notebooks/KWS_Audio_Evaluation.ipynb.   check the evaluate function when the input is .wav and see how it converts audio samples. The (128, 128) **samples** tensor can be stored as .npy

**Comment by rotx-maxim** [comment]
Please also see https://github.com/MaximIntegratedAI/ai8x-training/pull/201. If that doesn't address it, please open a new issue in that repo.
