### ISSUE TITLE
sample tinierssd evaluation after synthesis throwing errors

### ISSUE THREAD

**Issue by nikky4D** [MaximIntegratedAI/ai8x-synthesis#293]
I am running evaluation on the tinierssd weights saved in trained from the repo. However, I am getting the error, and everything pauses after:

![image](https://user-images.githubusercontent.com/7451106/235170561-a7beaaab-f047-4536-a84f-24c4ee83843d.png)

Can someone direct me as to what I can do to fix it?

My full printout is this:

![image](https://user-images.githubusercontent.com/7451106/235176155-ed36a9c0-b3a2-4095-b919-dcded5959ad7.png)

I am able to evaluate other models: cifar10, mnist. But this keeps happening for tinierssd with SVHN

**Comment by nikky4D** [comment]
I was able to fix it by changing the workers input to 0 in the train.py

**Comment by rotx-maxim** [comment]
Thanks for your feedback! We haven't seen this one, but we have seen cases where it requires --workers=1. Does it work only with 0, or also with 1? 
It's a GPU resources limitation.

**Comment by nikky4D** [comment]
I've tried it with --workers = 1, and I get the same error, only this time, a single pair, and not 4 pairs of the error lines

![image](https://user-images.githubusercontent.com/7451106/235195379-9c38f015-8a6c-4a03-a086-e6560c3694ec.png)

**Comment by rotx-maxim** [comment]
Thanks again! We will add this to the documentation.
