### ISSUE TITLE
Test results with a pretrained Camvid

### ISSUE THREAD

**Issue by kirilllzaitsev** [MaximIntegratedAI/ai8x-synthesis#299]
Using the `gen-demos-max78000.sh` script to synthesize a Camvid model on MAX78000:
```
python ai8xize.py --test-dir $TARGET --prefix camvid_unet --checkpoint-file trained/ai85-camvid-unet-large-fakept-q.pth.tar --config-file networks/camvid-unet-large-fakept.yaml $COMMON_ARGS --overlap-data --mlator --no-unload --max-checklines 8192 --new-kernel-loader --overwrite "$@"
```

and SerialLoader.py from aisegment_unet-demo to test the inference pipeline, I arrive at these predictions:
![image](https://github.com/MaximIntegratedAI/ai8x-synthesis/assets/44346535/80dfafc3-03d6-4cd2-900c-c56de832c537)
displayed by:
```
ax[0].imshow(img_resize1)
ax[1].imshow(colors, cmap="Greys")
ax[2].imshow(img_resize1)
ax[2].imshow(colors, cmap="Greys", alpha=0.2)
```

While some masks look correct (the top part), I want to ask if stripped patterns and the quality of prediction, in general, are expected from a trained model `trained/ai85-camvid-unet-large-fakept-q.pth.tar`.

**Comment by aniktash** [comment]
The demo project for camvid is UNet-highres-demo which has 4 output classes for buildings, plants, sky, and unknown.  Please use the SerialLoader.py in UNet-highres-demo\Utility if you would like to segment the scenery images. 
![Figure_1](https://github.com/MaximIntegratedAI/ai8x-synthesis/assets/48036488/9285b4ca-f490-4171-b8d7-f9197e881bc3)

The aisegmentation_unet-demo is for the segmentation of portrait face images and has 2 classes for face and background. The SerialLoader in this project is slightly different.
![Figure_2](https://github.com/MaximIntegratedAI/ai8x-synthesis/assets/48036488/c93adaed-0ff0-4070-b2a7-48c02230eb52)
