### ISSUE TITLE
out_offset in yaml file

### ISSUE THREAD

**Issue by jason850124** [MaximIntegratedAI/ai8x-synthesis#301]
Sorry, I'm the first time to use the MAX78000 EVKit, I can't totally understand how to set the value of the out_offset in yaml file, did I need to calculate it depending on something need to be noticed? Thank you so much!

Best regards,
Jason

**Comment by rotx-maxim** [comment]
Data memory (activation memory) holds the input to a layer as well as its output. Therefore, it's logical that the input has to be consumed before the output is written.
The easiest way to do this is to ensure there is no overlap between where the input is stored, and where the output is stored.
'out_offset' is a byte offset into that memory. It defaults to 0 for the input, and has to be specified for all other layers.
For very simple networks, it's enough to switch back and forth between 0 and half the data memory (see for example, `networks/mnist-chw-ai85.yaml`). For networks that use residuals, the output of a layer needs to stick around to be used in a later layer, not just the very next layer. In those cases, enough memory needs to be allocated to hold the intermediate output. If you have the dimensions (and the number of channels modulo 64) then that number is relatively simple to calculate - X*Y*M (where M is the number of passes, 1 for anything between 1 and 64 channels, higher for more than 64 channels). The synthesis tool (izer) will also complain if not enough memory is allocated.
There are more examples in the `networks/` folder of this repository.

**Comment by jason850124** [comment]
Hi! Rotx,

Thanks for your reply, I understand how to set the value of yaml file now, but there is one thing that makes me confused is when the output channels are more than 64, for example the output shape is 128x10x10, and output_offset is 0x2000, in the first 64 channels will occupy the memory to 0x2000+4x10x10, and I wanna know the output_offset of the left 64 channels is following the 0x2000+4x10x10?

**Comment by jason850124** [comment]
Hi! Rotx,

Thanks for your reply, your explains are totally clearly, I can design my own specific memory now!

Best regards,
Jason
