### ISSUE TITLE
clarification on the ai87_fpndetector yaml for memory setup

### ISSUE THREAD

**Issue by nikky4D** [MaximIntegratedAI/ai8x-synthesis#311]
In the .yaml description of the ai87_fpndetector, the intro comments describe the planned memory setup. I am confused as to some of the numbers there. 

First, why use 121, and not 126 in the Class predictions?  In the regression, you only use 24 = 6*4. 

Second, I'm a bit confused on the address mapping in classification and regression. Could you please explain how the memory is mapped here. For example, for the classification, for the address range 0x0000-0xA000, is it correct to say it is calculated as 4 bytes per 0 hence 0xA000 == 40960 * 4 = 163840 which is the rounded up version of 32*40*121=154880? 
Also, in the regression, the numbers seem to be too little for the data. For eg: for regression layer 4x5x64, the memory is planned for 0xF000-0xF0A0 = 640 which is much less that 4*5*64 = 1280,. Similarly for others like the 32x40x64 layer 0xF6E0:0x10AE0 = 20480 << 32*40*64 = 81920. 

What is the recommended way to define these memory allocations in a systematic fashion especially if I modify the filter shapes eg increase filter sizes like changing 32x40 to 40x80 as when I setup the model with a different image input size? The memory locations seem to be referenced in the nms.c that is called in the sdk examples here [L222](https://github.com/Analog-Devices-MSDK/msdk/blob/54922aa49f3beb75a84199b1106812d712efc77b/Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/src/cnn/nms.c#L222). So any changes would then need to be propagated to the example to make it work for a new but similar model.

```
# Model Outputs:
#
# Class predictions   : (32x40 + 16x20 + 8x10 + 4x5) * 6 * 21 = 10200 * 21
#                       0x0000 - 0xD480 (1700 x 32: wide & multi-pass)
#
# 0x0000 - 0xA000: 32x40x121 (&wide) 
# 0xA000 - 0xC800: 16x20x121 (&wide)
# 0xC800 - 0xD200: 8x10x121 (&wide)
# 0xD200 - 0xD480: 4x5x121 (&wide)
#
# Location predictions: (32x40 + 16x20 + 8x10 + 4x5) * 6 * 4 = 10200 * 4
#                       0xD500 - 0xEF90 (1700 x 4)
#
# 0xD500 - 0xE900: 32x40x24
# 0xE900 - 0xEE00: 16x20x24
# 0xEE00 - 0xEF40: 8x10x24
# 0xEF40 - 0xEF90: 4x5x24
#
#
# FPN_out_4_5  : 0xF000-0xF0A0 (4x5x64, gap:1, protect after Layer 34 until x)
# FPN_out_8_10 : 0xF0A0-0xF1E0 (8x10x64, protect after Layer 37 until x)
# FPN_out_16_20: 0xF1E0-0xF6E0 (16x20x64, protect after Layer 40 until x)
# FPN_out_32_40: 0xF6E0-0x10AE0 (32x40x64, protect after Layer 43 until x)
#
```

**Comment by seldauyanik-maxim** [comment]
1) You are correct, the comment has a typo there: the number of channels is 126 as you also pointed out (6 * 21). From layers 52 and after you can see the number of channels is 126 requiring two-pass.

In general, before below further explanations, the main trick is not to multiply channel components when calculating memory space needed.
(4x5x64=1280 intuition is not valid) 
As parallel data memory instances handle data sharing among channel dimension, you should only consider whether number of channels necessitate a multi-pass or not.
See [link ](https://github.com/MaximIntegratedAI/ai8x-synthesis#data-memory )for details

2) Both wide output and multi-pass calculation is a little tricky here, sample address calculation for 32x40 resolution:
    32 x 40 
    x 4 (as wide output fills a word per channel, for shared 4 processors each pixel takes 4 words in same memory)
    x 2 (as multipass is used see: [link](https://github.com/MaximIntegratedAI/ai8x-synthesis#multi-pass) for details)
    x 4 (for incrementing memory address properly per pixel)
    Making 4096: 0xA000
   
3) Sample address calculation for regression layer 4x5 resolution and 24 channels:
   4x5
   x 4 (for incrementing memory address properly per pixel): making 0x50

4) Your example is actually from an intermediate layer (FPN_out_4_5) where output is 4x5 resolution and 64 channels:
    64 channels does not need multi-pass, however, that layer has another special condition: uses a write gap of 1 for latter ease of element-wise operations, therefore correct calculation would be
   4x5
   x 2 (for interleaved output see: [link ](https://github.com/MaximIntegratedAI/ai8x-synthesis#write_gap-optional)for details)
   x 4 (for incrementing memory address properly per pixel): making 0xA0

5) The addresses for location and classification outputs should be provided to NMS as you already pointed out.  As you may have noticed, the class addresses can be non-continuous (4 addresses for 4 resolutions) but for locations NMS has assumed they continue from a single starting address. As far as you provide those locations and they do not overlap, you can use any memory location. Best practice can be to note down those locations  as once they are written, you should not overwrite those memory locations for the needs of other latter intermediate layers.

**Comment by nikky4D** [comment]
@seldauyanik-maxim  Thank you for the reply. It clarified a lot of confusion. I think I can make my way through now.
