### ISSUE TITLE
Problems at quantizing

### ISSUE THREAD

**Issue by liuyuxivapor** [MaximIntegratedAI/ai8x-synthesis#317]
Hi, there.
I have finished the training part and doing quantizing. But it gives the ERROR `TypeError: sequence item 1: expected str instance, NoneType found`.
Tracing back here.
`Model keys (state_dict):
conv1.weight, bn1.weight, bn1.bias, bn1.running_mean, bn1.running_var, bn1.num_batches_tracked, conv2.weight, bn2.weight, bn2.bias, bn2.running_mean, bn2.running_var, bn2.num_batches_tracked, conv3.weight, fc.weight, fc.bias
Traceback (most recent call last):
  File "quantize.py", line 29, in <module>
    main()
  File "/home/vapor/code/AIoT/ai8x-synthesis/izer/quantize.py", line 297, in main
    convert_checkpoint(args.input, args.output, args)
  File "/home/vapor/code/AIoT/ai8x-synthesis/izer/quantize.py", line 158, in convert_checkpoint
    bias_name = '.'.join([layer, operation, 'bias'])
TypeError: sequence item 1: expected str instance, NoneType found`
Bias exists but cannot be joined. Thanks a lot if anyone could help with this!

**Comment by alicangok** [comment]
Hi,

We will gladly try to help you if you could provide us your checkpoint (qat_best.pth.tar) and model files?

I see that you have started a repo for this project. Perhaps you could upload the log directory containing the checkpoint files (best.pth.tar, qat_best.pth.tar) and the .log (day-time.log) file, and we can go from there.

**Comment by liuyuxivapor** [comment]
Thanks for checking this! I have just pushed log files in the `latest_log_dir` in [my repo](https://github.com/liuyuxivapor/ai8x_approx), where I got trapped.

**Comment by alicangok** [comment]
Unfortunately `latest_log_dir` only contains the shortcut. The checkpoints (*.pth.tar) and the log files are found in the actual log directory, which I don't see in the repo.

Nevertheless, I identified the source of your issue. Your custom models in your repo (such as [ai85net-fpr](https://github.com/liuyuxivapor/ai8x_approx/blob/master/ai8x-training/models/ai85net-fpr.py)) use torch.nn layers. However for deployment on the device, you would need to use the [predefined modules](https://github.com/MaximIntegratedAI/ai8x-training#list-of-predefined-modules), for the quantization and batchnorm weight fusing operations to work. You may access the full list of modules at [ai8x.py](https://github.com/MaximIntegratedAI/ai8x-training/blob/develop/ai8x.py).

For example, `x = relu(self.bn1(self.conv1(x)))` should be replaced by `x = self.conv1bn(x)` where `self.conv1bn = ai8x.FusedConv2dBNReLU(1, 16, 3, stride=1, padding=1, bias=False, batchnorm='Affine')`.

**Comment by liuyuxivapor** [comment]
Got it, perhaps because of not using ai8x functions and not obeying the bias rules of ai8x functions for quantizing. Thanks!
