### ISSUE TITLE
Flatten and Linear of generating C model

### ISSUE THREAD

**Issue by liuyuxivapor** [MaximIntegratedAI/ai8x-synthesis#318]
Hi, there. I got trapped again in the network part. The last layer of this simple model seems not to work, ` Layer 3: "flatten" exceeds supported input dimensions (512 * 1 > 256)).` 
I supposed it might need an 8-bit data until I found an example in [this maxim guide link](https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/Guides/YAML%20Quickstart.md). In example 4, layer 6, the input data is further larger than 8-bit after flattened. So I am wondering how to solve this.

Another question is over this. I tried setting the flatten of Layer 3 as False, but it gives the error about Layer2-output and Layer3-input needing different number of processors. So I d like to know about this after the first problem is solved. Thanks a lot.

```\# Define layer parameters in order of the layer sequence
layers:
  \# ai8x.FusedConv1dBNReLU(1, 8, kernel_size=3, stride=1, padding=1, bias=True, batchnorm='Affine')
  \- data_format: CHW
    op: Conv1d
    pad: 1
    activate: ReLU
    kernel_size: 3
    stride: 1
    processors: 0x0000000000000001
    out_offset: 0x0000

 \# ai8x.FusedConv1dBNReLU(8, 16, kernel_size=3, stride=1, padding=1, bias=True, batchnorm='Affine')
  \- op: Conv1d
    pad: 1
    activate: ReLU
    kernel_size: 3
    stride: 1
    processors: 0x0000000000000ff0
    out_offset: 0x2000

  \# ai8x.FusedConv1dBNReLU(16, 2, kernel_size=3, stride=1, padding=1, bias=True, batchnorm='Affine')
 \- op: Conv1d
    pad: 1
    activate: ReLU
    kernel_size: 3
    stride: 1
    processors: 0x000000000ffff000
    out_offset: 0x0000

  \# Flatten & ai8x.Linear(512 * 2, 512)
  \- op: Linear
    flatten: True
    activate: None
    processors: 0xffffffffffffffff
    out_offset: 0x2000```

**Comment by alicangok** [comment]
> The last layer of this simple model seems not to work

Could you please specify which model? There are multiple new models in your repo.

But the error message has nothing to do with the bit-width. It simply states that the product of your input dimensions has to be less than 256. I see that the input dimensions the flatten layer is `512 * 1`, which I found a bit weird. Flatten operation is used when you want to transform a 2-Dimensional data into 1D. If your data is already 1D, then there is no need to use flatten.

> I supposed it might need an 8-bit data until I found an example in [this maxim guide link](https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/Guides/YAML%20Quickstart.md). In example 4, layer 6, the input data is further larger than 8-bit after flattened.

All intermediate layer outputs are 8-bit. Flattening does not change the bit-width.

> Another question is over this.  I tried setting the flatten of Layer 3 as False.

Again, if you could specify which model, that would be great..

**Comment by liuyuxivapor** [comment]
Sorry for not made my question clear. The yaml file of my model is in the code block in the final part of my comment above, whose last layer is 
``` 
 # Flatten & ai8x.Linear(512 * 2, 512)
  - op: Linear
    flatten: True
    activate: None
    processors: 0xffffffffffffffff
    out_offset: 0x2000
```
Example 4 - layer 6 means
```
# +++++++++++++++++++++ layer 6:self.fc = ai8x.Linear(30*64*64, 2, bias=True)
- op: mlp
  flatten: true
  out_offset: 0x1000
  output_width: 32
  processors: 0x000000003fffffff
```
I wonder what does `512*1`mean in my ERROR, and it is no larger than 30*64*64 in the example above. All model files in my repo is about dct4. Thanks!

**Comment by liuyuxivapor** [comment]
Thanks! Maybe I could try this light model.

**Comment by bitmorse** [comment]
Had the same issue! This helped, thanks!
