### ISSUE TITLE
MAX78000 tinySSD yaml file memory question

### ISSUE THREAD

**Issue by michame951** [MaximIntegratedAI/ai8x-synthesis#328]
Hello! This is my first time using MAX78000. I saw the sample code for TinySSD, but I don't know how to calculate the memory allocation for each tier. I think it should be CNN.C that displays the data configuration of each layer. 
![image](https://github.com/MaximIntegratedAI/ai8x-synthesis/assets/101703394/065a7d44-68f6-4d63-bd85-ef9511f27807)

This should correspond to the layer offset for each layer of the YAML file.
https://github.com/MaximIntegratedAI/ai8x-synthesis/blob/develop/networks/svhn-tinierssd.yaml

Below is my question
1. Could you please tell me how to give the address of offset for each layer? How to plan it?
2. Why does layer0 need to set out_offset and in_offset at the beginning?
![image](https://github.com/MaximIntegratedAI/ai8x-synthesis/assets/101703394/fd5f8c07-ebe6-4cc8-9e98-18393cc3775a)
3. The data entered into Layer0 at the beginning is 3x74x74 = 16428 = 0x402C. So the memory occupied is 0x50402000+0x402C = 0x5040 602C?
4. Why is layer2 out_offset changed to 0x1000?
![image](https://github.com/MaximIntegratedAI/ai8x-synthesis/assets/101703394/49cee7b9-7d33-4bed-8d98-cbdd1faf5d1a)

Thank you very much for your help.

**Comment by ermanok** [comment]
Hello michame951,

Here are the answers to your questions:

	1. The _in_offset_ and _out_offset_ of a layer specifies the memory offset of the input and the output data of a layer. These offset values are determined according to the _processors_ and the _output_processors_ of the layer. While determining these values, the easiest way is setting the offsets such that the input and output data do not coincide with each other. There are two ways to ensure this: 
              - Using different _processors_ and _output_processors_
              - Setting enough gap between _in_offset_ and _out_offset_. For instance if the input data is 32x32 and _in_offset_ is 0x2000, the _out_offset_ should be at least 0x2000 + 0x1000 (=32x32x4) = 0x3000. 
	For some cases, the _in_offset_ and _out_offset_ should coincide, due to the data size and memory limitations. In this case, the hardware should consume the part of the input data before writing the output on that memory location. This is something hard to guess before making some tests on the hardware. Running Known Answer Tests (KAT) to set the _in_offset_ and _out_offset_ is the best approach in such situations. 
	2. _In_offset_ is not necessary in this case. The default value of the _in_offset_ for the initial layer is 0 (see [here](https://github.com/MaximIntegratedAI/ai8x-synthesis?tab=readme-ov-file#in_offset-optional)). I think the model still works if you delete that line..
	3. The data is stored in HWC format and each memory block stores 4 channel of the data. So each pixel data in a memory block is represented by 4 bytes. If the number of channels in any memory block is less than 4, each pixel still uses 4 bytes with unused bytes. So, for your question the answer is 0x50402000+0x5590(=4x74x74) = 0x50407590.
	4. This question is partly answered by Q1. The layer uses same input and output processors, so if the _out_offset_ is not properly set, the layer can write the output data on the input data before consuming, which yields wrong output values. Then, the _out_offset_ should be different than the _in_offset_. As the input data spans from the address 0x2000 to the end of the memory space (0x8000), the _out_offset_ is set to a lower memory address (0x1000).

You can also find more information about the data memory of the CNN layers in the [documentation]( https://github.com/MaximIntegratedAI/ai8x-synthesis?tab=readme-ov-file#data-memory).

**Comment by michame951** [comment]
Hi @ermanok ,
Got it, thanks for your support.
