### ISSUE TITLE
Multiple Passes through the Same Layer?

### ISSUE THREAD

**Issue by TonyVT0** [MaximIntegratedAI/ai8x-synthesis#356]
Hi,

I have a network trained on ai8x layers, but there is one section of the network that requires multiple passes through the same layer. Is it possible to create a YAML file for this type of network that can be converted into C code with the synthesis tool provided? 

For a specific example, let us have four intermediate outputs at different feature maps. Is it possible for each of the outputs to be fed into the same layer creating four new outputs? If so, could you provide a sample example for this YAML structure?

Thanks in advanced.

**Comment by ermanok** [comment]
This is possible with weight sharing. This can be done using [`weight_source`](https://github.com/analogdevicesinc/ai8x-synthesis/tree/develop#weight_source-optional) parameter in the yaml file. So, if you need to use a layer 4 times in a network, you have to define the same layer 4 times in the yaml file, whose `weight_source` parameters map to the same layer. You can see the usage of this parameter in [FPNDetector](https://github.com/analogdevicesinc/ai8x-synthesis/blob/develop/networks/ai87-pascalvoc-fpndetector.yaml) example.
